version: "3"
services:

  app:
    container_name: node-mongo
    restart: always
    build: . # location of Dockerfile
    ports:
      - "3333:3333"
    expose:
      - "3333"
    depends_on:
      - mongo # depends_on only means the container is running, not the db server inside it
    command: sh -c "/wait && npm start" # so, we use the wait script (see Dockerfile)

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    volumes:
      - "./data/db:/data/db"
    ports:
      - "27017:27017"
    expose:
      - "27017"
